# SPDX-License-Identifier: MIT

# Copyright (C) 2020 Malinovsky Rodion (rodionmalino@gmail.com)

[credentials]
server = "SERVER_URL"
username = "LOGIN"
password = "PASSWORD"

[options]
# Week number
weeks = 30
# List of users
users = ["User1", "User2"]